# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432
    networks:
      - postgres

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: dev
        PGADMIN_CONFIG_SERVER_MODE: 'False'

      ports:
        - 5050:80
      networks:
      - postgres

networks:
  postgres: